# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:            Gamers Hub
email:            projghub@gmail.com
description:      Articles on Game Development and Gaming
baseurl:          '' # The subpath of your site, e.g. /blog
url:              'https://blog.gamershub.in/' # The base hostname & protocol for your site
github_username:  gamers-hub
twitter_username: gamershubindia

markdown:  kramdown
permalink: pretty
paginate:  12

gems:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

sass:
  style: compressed

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  sujay:
    name:             Sujay Kundu
    bio:              Author & developer of Gamers Hub
    gravatar:         https://s.gravatar.com/avatar/fe9f606b05ba27d8ab9469856ccefcc2?s=150
    email:            mail@sujaykundu.com
    website:          https://sujaykundu.com
    github_username:  sujaykundu777
    twitter_username: xplor4r